
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.awt.Toolkit;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

 
public class MenuGADs extends javax.swing.JFrame {

        public MenuGADs() {
        createAndShowGUI();
    }
    private static void centerFrameOnScreen(JFrame frame) {
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (screenSize.width - frame.getWidth()) / 2;
        int y = (screenSize.height - frame.getHeight()) / 2;
        frame.setLocation(x, y);
    }

    private static void createAndShowGUI() {
        JFrame frame = new JFrame("Menu Gads");
        frame.setSize(800, 600);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        centerFrameOnScreen(frame);

        // Panel principal con layout BorderLayout
        JPanel mainPanel = new JPanel(new BorderLayout());

        // Panel para los botones con layout GridBagLayout
        JPanel buttonPanel = new JPanel(new GridBagLayout());
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.insets = new Insets(10, 10, 10, 10); // Espacio a los lados

        // Botones
        JButton btnModificar = createStyledButton("Gestionar Gads");
        JButton btnAgregar = createStyledButton("Gestionar Agencias");
        JButton btnDescargar = createStyledButton("Consultas fecuentes");
        JButton btnUbicacion = createStyledButton("Gestionar Ubicaciones");
        JButton btnRegresar = createStyledButton("Regresar");

        // Agrega ActionListener a cada botón para manejar eventos
        btnModificar.addActionListener(e -> {
            frame.dispose(); // Cierra la ventana actual
            VerGAD menu = new VerGAD();
            menu.setVisible(true);
        });

        btnAgregar.addActionListener(e -> {
            frame.dispose(); // Cierra la ventana actual
            VerAgencias menu = new VerAgencias();
            menu.setVisible(true);
        });

        btnDescargar.addActionListener(e -> {
            frame.dispose(); // Cierra la ventana actual
            VistaEmpleados menu = new VistaEmpleados();
            menu.setVisible(true);
        });
        
        btnUbicacion.addActionListener(e -> {
            frame.dispose(); // Cierra la ventana actual
            InterfazUbicacion menu = new InterfazUbicacion();
            menu.setVisible(true);
        });

        btnRegresar.addActionListener(e -> {
            frame.dispose(); // Cierra la ventana actual
            MenuInterfazGUI menuInterfaz = new MenuInterfazGUI();
            menuInterfaz.initUI();
        });

        // Agrega botones al panel con GridBagLayout
        buttonPanel.add(btnModificar, gbc);
        gbc.gridy++;
        buttonPanel.add(btnAgregar, gbc);
        gbc.gridy++;
        buttonPanel.add(btnDescargar, gbc);
        gbc.gridy++;
        buttonPanel.add(btnUbicacion, gbc);
        gbc.gridy++;
        buttonPanel.add(btnRegresar, gbc);

        // Agrega el panel de botones al panel principal
        mainPanel.add(buttonPanel, BorderLayout.CENTER);

        // Agrega el panel principal al frame
        frame.getContentPane().add(mainPanel);

        frame.setVisible(true);
    }

    private static JButton createStyledButton(String text) {
        JButton button = new JButton(text);
        button.setFont(new Font("Arial", Font.BOLD, 16));
        button.setPreferredSize(new Dimension(350, 50));
        return button;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuGADs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuGADs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuGADs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuGADs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        SwingUtilities.invokeLater(() -> {
            createAndShowGUI();
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
